<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Albany Fajar Islami">
<meta name="dcterms.date" content="2024-01-19">

<title>PENGARUH EKSPOR DAN IMPOR TERHADAP PERTUMBUHAN EKONOMI DI INDONESIA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="index_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="index_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PENGARUH EKSPOR DAN IMPOR TERHADAP PERTUMBUHAN EKONOMI DI INDONESIA</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Albany Fajar Islami </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 19, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Pertumbuhan ekonomi adalah indikator utama kesejahteraan suatu negara, dan kemampuan ekspor dan impor untuk berkontribusi pada pertumbuhan ekonomi menjadi fokus perhatian. Ekspor dapat memperluas pasar bagi produk-produk nasional, meningkatkan pendapatan, dan menciptakan lapangan kerja. Di sisi lain, impor membawa inovasi, teknologi, dan barang konsumsi yang mungkin sulit diproduksi secara efisien di dalam negeri.</p>
<p>Dalam konteks Indonesia, sebagai negara dengan ekonomi yang terus berkembang, pemahaman mendalam tentang hubungan antara ekspor, impor, dan pertumbuhan ekonomi sangat penting. Periode 1999-2020 yang menjadi cakupan penelitian mencakup periode signifikan dalam sejarah ekonomi Indonesia, termasuk periode krisis keuangan Asia pada tahun 1997 dan proses globalisasi ekonomi yang semakin memperkuat keterkaitan antarnegara. Dengan menggunakan metode penelitian olah data menggunakan RStudio, penelitian ini bertujuan untuk mengidentifikasi pola hubungan, signifikansi, dan dampak dari ekspor dan impor terhadap pertumbuhan ekonomi Indonesia</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini bertujuan untuk mendalami hubungan antara ekspor, impor, dan pertumbuhan ekonomi Indonesia dalam rentang waktu 1999-2020. Fokus utama penelitian adalah memahami bagaimana ekspor dapat memperluas pasar produk nasional, meningkatkan pendapatan, dan menciptakan lapangan kerja, sementara impor membawa inovasi, teknologi, dan barang konsumsi yang sulit diproduksi secara efisien di dalam negeri. Rentang waktu penelitian mencakup periode krisis keuangan Asia pada tahun 1997 dan proses globalisasi ekonomi yang semakin memperkuat keterkaitan antarnegara. Metode penelitian yang digunakan adalah olah data menggunakan RStudio, yang diharapkan dapat mengidentifikasi pola hubungan, signifikansi, dan dampak dari ekspor dan impor terhadap pertumbuhan ekonomi Indonesia. Dengan demikian, penelitian ini berpotensi memberikan wawasan mendalam tentang faktor-faktor yang mempengaruhi dinamika ekonomi Indonesia, memungkinkan pengambilan keputusan yang lebih baik di bidang kebijakan ekonomi dan perdagangan.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan uraian latar belakang diatas maka yang menjadi masalah pokok pada penelitian ini adalah:</p>
<ol type="1">
<li><p>Bagaimana hubungan antara volume ekspor Indonesia dan pertumbuhan ekonomi selama periode 1999-2020, dan apakah terdapat pola atau tren tertentu yang dapat diidentifikasi dari data tersebut?</p></li>
<li><p>Sejauh mana impor memiliki dampak terhadap pertumbuhan ekonomi Indonesia selama rentang waktu yang sama, dan apakah ada perubahan signifikan dalam korelasi antara impor dan pertumbuhan ekonomi setelah periode krisis keuangan Asia pada tahun 1997?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian ini adalah untuk mengidentifikasi hubungan antara ekspor dan impor Indonesia dengan pertumbuhan ekonomi selama periode 1999-2020. Penelitian bertujuan mengeksplorasi dampak ekspor terhadap pendapatan dan lapangan kerja, serta menganalisis peran impor dalam konteks pertumbuhan ekonomi negara.</p>
<p>Adapun manfaat dari penelitian ini antara lain:</p>
<ol type="1">
<li>Manfaat Teoritis</li>
</ol>
<p>Manfaat teoritis dari penelitian ini mencakup kontribusi terhadap literatur ekonomi dengan menyediakan wawasan mendalam tentang hubungan kompleks antara ekspor, impor, dan pertumbuhan ekonomi. Penelitian ini dapat memperkaya teori ekonomi internasional dan menyumbang pada pemahaman tentang dinamika ekonomi negara berkembang, seperti Indonesia.</p>
<ol start="2" type="1">
<li>Manfaat Praktis</li>
</ol>
<ol type="A">
<li>Bagi Penulis</li>
</ol>
<p>Hasil penelitian ini memberikan manfaat praktis bagi penulis dengan meningkatkan keahlian analisis data menggunakan RStudio dan memperdalam pemahaman tentang ekonomi internasional. Penulis dapat mengaplikasikan keterampilan ini dalam penelitian lanjutan dan memberikan kontribusi pada pengembangan kebijakan ekonomi.</p>
<ol start="2" type="A">
<li>Bagi Instansi</li>
</ol>
<p>Hasil penelitian ini memberikan manfaat praktis bagi instansi terkait, seperti Kementerian Perdagangan atau Lembaga Statistik. Temuan ini dapat menjadi dasar untuk merumuskan kebijakan perdagangan dan ekonomi yang lebih efektif, memungkinkan instansi untuk mengarahkan sumber daya dengan lebih tepat dan mendukung pertumbuhan ekonomi yang berkelanjutan.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Untuk keperluan menunjang regresi multivariat yang dilakukan di Rstudio untuk penelitian ini antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<ol type="1">
<li>Ekspor</li>
</ol>
<p>Ekspor, menurut Lipsey (1995), merujuk pada seluruh penjualan barang yang dihasilkan oleh suatu negara dan diperdagangkan kepada negara lain dengan maksud memperoleh devisa. Dalam konteks ekonomi, ekspor melibatkan penjualan barang atau layanan dari produsen domestik ke konsumen atau bisnis di luar wilayah negara pengirim. Proses ekspor melibatkan aktivitas seperti produksi, distribusi, dan pemasaran produk di pasar internasional. Jenis produk yang diekspor dapat bervariasi dari barang manufaktur hingga komoditas alam, serta jasa seperti pariwisata atau layanan konsultasi. Ekspor memiliki peran vital dalam menggerakkan perekonomian suatu negara, karena dapat meningkatkan pendapatan, menciptakan lapangan kerja, dan meningkatkan daya saing industri domestik di pasar global. Negara-negara cenderung mengembangkan strategi ekspor sebagai bagian dari kebijakan ekonomi mereka untuk mengoptimalkan sumber daya dan meningkatkan pertumbuhan ekonomi. Faktor-faktor seperti stabilitas mata uang, kebijakan perdagangan, dan kondisi pasar internasional memainkan peran kunci dalam menentukan keberhasilan ekspor suatu negara. Dengan demikian, ekspor menjadi aspek integral dalam dinamika ekonomi global dan berkontribusi secara signifikan terhadap pembangunan ekonomi suatu negara. Menurut Salvatore (1997), ada beberapa motivasi di balik pelaksanaan ekspor oleh suatu negara, termasuk: a. Kebutuhan untuk memenuhi ragam kebutuhan yang tidak dapat dipenuhi sepenuhnya oleh produksi atau hasil dalam negeri, termasuk kebutuhan yang, meskipun bisa diproduksi secara lokal, lebih ekonomis jika diproduksi di luar negeri. b. Niat negara untuk meluaskan pasar untuk komoditas domestiknya sebagai upaya untuk meningkatkan sumber daya devisa yang dapat digunakan dalam kegiatan pembangunan ekonomi.</p>
<ol start="2" type="1">
<li>Impor</li>
</ol>
<p>Impor adalah kegiatan memasukkan barang atau jasa dari luar negeri ke dalam suatu negara. Ini merupakan elemen penting dalam perdagangan internasional yang melibatkan pembelian dan penggunaan produk atau layanan yang tidak diproduksi secara lokal. Proses impor memungkinkan suatu negara untuk memperoleh barang atau jasa yang tidak tersedia atau kurang efisien diproduksi di dalam negeri, melalui pembelian dari pasar global. Importasi mencakup sejumlah tahapan, termasuk proses perizinan, pembayaran bea masuk, dan pemenuhan persyaratan peraturan perdagangan internasional. Melalui impor, suatu negara dapat mendapatkan akses ke berbagai jenis barang, termasuk bahan baku, teknologi, dan produk konsumen yang mendukung keberlanjutan dan pertumbuhan ekonomi. Selain itu, impor juga dapat membawa dampak positif dalam meningkatkan variasi barang dan layanan yang tersedia di pasar domestik, mendorong inovasi, serta memberikan kontribusi terhadap diversifikasi ekonomi. Meskipun impor memberikan manfaat signifikan, pengaturan yang cermat diperlukan untuk menjaga keseimbangan perdagangan dan melindungi industri lokal agar tetap kompetitif. Oleh karena itu, impor tidak hanya sebagai alat untuk memenuhi kebutuhan, tetapi juga sebagai strategi yang cerdas untuk mengoptimalkan sumber daya dan meningkatkan kesejahteraan ekonomi suatu negara.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl) </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra) </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"The Data.xlsx"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">kbl</span>(dat) <span class="sc">%&gt;%</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>, <span class="st">"responsive"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">x</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">s</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">48665.5</td>
<td style="text-align: right;">24003.3</td>
<td style="text-align: right;">0.99</td>
</tr>
<tr class="even">
<td style="text-align: right;">62124.0</td>
<td style="text-align: right;">33514.8</td>
<td style="text-align: right;">4.92</td>
</tr>
<tr class="odd">
<td style="text-align: right;">56323.1</td>
<td style="text-align: right;">30962.1</td>
<td style="text-align: right;">3.64</td>
</tr>
<tr class="even">
<td style="text-align: right;">57105.8</td>
<td style="text-align: right;">31288.9</td>
<td style="text-align: right;">4.50</td>
</tr>
<tr class="odd">
<td style="text-align: right;">61034.5</td>
<td style="text-align: right;">32550.7</td>
<td style="text-align: right;">4.78</td>
</tr>
<tr class="even">
<td style="text-align: right;">71584.6</td>
<td style="text-align: right;">46524.5</td>
<td style="text-align: right;">5.03</td>
</tr>
<tr class="odd">
<td style="text-align: right;">85659.9</td>
<td style="text-align: right;">57700.9</td>
<td style="text-align: right;">5.69</td>
</tr>
<tr class="even">
<td style="text-align: right;">100798.6</td>
<td style="text-align: right;">61065.5</td>
<td style="text-align: right;">5.50</td>
</tr>
<tr class="odd">
<td style="text-align: right;">114101.0</td>
<td style="text-align: right;">74473.4</td>
<td style="text-align: right;">6.35</td>
</tr>
<tr class="even">
<td style="text-align: right;">137020.4</td>
<td style="text-align: right;">129197.3</td>
<td style="text-align: right;">6.01</td>
</tr>
<tr class="odd">
<td style="text-align: right;">116510.0</td>
<td style="text-align: right;">96829.2</td>
<td style="text-align: right;">4.63</td>
</tr>
<tr class="even">
<td style="text-align: right;">157779.0</td>
<td style="text-align: right;">135663.3</td>
<td style="text-align: right;">6.22</td>
</tr>
<tr class="odd">
<td style="text-align: right;">203496.6</td>
<td style="text-align: right;">177435.7</td>
<td style="text-align: right;">6.17</td>
</tr>
<tr class="even">
<td style="text-align: right;">190031.8</td>
<td style="text-align: right;">191691.0</td>
<td style="text-align: right;">6.03</td>
</tr>
<tr class="odd">
<td style="text-align: right;">182551.9</td>
<td style="text-align: right;">186628.7</td>
<td style="text-align: right;">5.56</td>
</tr>
<tr class="even">
<td style="text-align: right;">176292.7</td>
<td style="text-align: right;">178178.8</td>
<td style="text-align: right;">5.01</td>
</tr>
<tr class="odd">
<td style="text-align: right;">150393.3</td>
<td style="text-align: right;">142694.5</td>
<td style="text-align: right;">4.88</td>
</tr>
<tr class="even">
<td style="text-align: right;">144489.7</td>
<td style="text-align: right;">135652.8</td>
<td style="text-align: right;">5.03</td>
</tr>
<tr class="odd">
<td style="text-align: right;">168828.2</td>
<td style="text-align: right;">156985.5</td>
<td style="text-align: right;">5.07</td>
</tr>
<tr class="even">
<td style="text-align: right;">180012.7</td>
<td style="text-align: right;">188711.2</td>
<td style="text-align: right;">5.17</td>
</tr>
<tr class="odd">
<td style="text-align: right;">167683.0</td>
<td style="text-align: right;">170727.4</td>
<td style="text-align: right;">5.02</td>
</tr>
<tr class="even">
<td style="text-align: right;">163306.5</td>
<td style="text-align: right;">141568.8</td>
<td style="text-align: right;">5.05</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Penelitian ini menggunakan data sekunder dengan bentuk data time series 1999-2020, data yang dipakai ialah data yang telah diolah dengan sumber Badan Pusat Statistik.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'The Data.xlsx'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x<span class="sc">+</span>s, <span class="at">data=</span>dat)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>x,dat<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Ekspor dan Impor"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>) <span class="co">#membuat garis horizontal di y=0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh error terhadap Ekspor dan Impor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>y,dat<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Pertumbuhan Ekonomi"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh error terhadap Pertumbuhan Ekonomi</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode analisis dalam penelitian ini dimulai dengan pengumpulan data ekonomi terkait ekspor, impor, dan pertumbuhan ekonomi di Indonesia dari tahun 1999 hingga 2020. Data yang terkumpul kemudian disiapkan dengan melakukan pembersihan data untuk menangani nilai yang hilang, melakukan pemformatan variabel, dan konversi jenis data jika diperlukan. Penggunaan fungsi read_excel dari paket readxl dalam R memungkinkan pembacaan data dari file Excel dan mengubahnya menjadi format data frame. Setelah tahap persiapan data, dilanjutkan dengan analisis data eksploratif (EDA) yang melibatkan visualisasi hubungan antar variabel. Dalam konteks ini, sebuah diagram pencar (plot(x, y)) dibuat untuk memberikan gambaran visual tentang korelasi antara variabel ekspor, impor, dan pertumbuhan ekonomi. Langkah selanjutnya melibatkan uji korelasi Pearson untuk mengukur kekuatan dan arah hubungan antara variabel-variabel tersebut. Hasilnya, dengan koefisien korelasi sebesar 0.503, menunjukkan adanya hubungan positif antara ekspor, impor, dan pertumbuhan ekonomi. Untuk pemahaman lebih mendalam, dilakukan analisis regresi linear dengan menggunakan model regresi lm(y ~ x). Hasil regresi menunjukkan bahwa variabel ekspor dan impor memiliki dampak positif terhadap pertumbuhan ekonomi, dengan koefisien regresi masing-masing sebesar 5.156e-06 dan 3.824e+00. Dengan demikian, metode analisis ini mencakup langkah-langkah dari pengumpulan dan persiapan data hingga analisis eksploratif dan regresi linear, memberikan pemahaman komprehensif tentang hubungan ekspor, impor, dan pertumbuhan ekonomi di Indonesia.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Pada bagian ini dapat ditampilkan data dan visualisasi data yang telah dikumpulkan.</p>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Std.Error</th>
<th>t-value</th>
<th>Prob (.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intecerpt</td>
<td>1.983e+00</td>
<td>8.927e-01</td>
<td>2.221</td>
<td>0.0387</td>
</tr>
<tr class="even">
<td>X</td>
<td>5.770e-05</td>
<td>2.170e-05</td>
<td>2.659</td>
<td>0.0155</td>
</tr>
<tr class="odd">
<td>S</td>
<td>-3.865e-05</td>
<td>1.803e-05</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'The Data.xlsx'</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x<span class="sc">+</span>s, <span class="at">data=</span>dat)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x + s, data = dat)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.87313 -0.31610  0.07771  0.52296  1.11460 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  1.983e+00  8.927e-01   2.221   0.0387 *
x            5.770e-05  2.170e-05   2.659   0.0155 *
s           -3.865e-05  1.803e-05  -2.144   0.0452 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8828 on 19 degrees of freedom
Multiple R-squared:  0.4338,    Adjusted R-squared:  0.3742 
F-statistic: 7.279 on 2 and 19 DF,  p-value: 0.004499</code></pre>
</div>
</div>
<p>Model regresi linear ini memberikan gambaran tentang hubungan antara pertumbuhan ekonomi Indonesia ((y)) dengan variabel ekspor ((x)) dan impor ((s)). Nilai intercept sebesar 1.983 mengindikasikan estimasi pertumbuhan ekonomi ketika nilai ekspor dan impor mencapai nol, meskipun interpretasi praktisnya mungkin terbatas. Koefisien positif untuk variabel ekspor (5.770e-05) menggambarkan bahwa peningkatan ekspor berkontribusi positif terhadap pertumbuhan ekonomi. Sementara itu, koefisien negatif untuk variabel impor (-3.865e-05) menunjukkan adanya hubungan negatif antara impor dan pertumbuhan ekonomi, yang berarti semakin tinggi nilai impor, pertumbuhan ekonomi kemungkinan akan lebih rendah. Residual standard error dengan nilai 0.8828 mengukur seberapa akurat model dapat memprediksi pertumbuhan ekonomi berdasarkan variabel ekspor dan impor. R-squared sebesar 0.4338 menunjukkan bahwa sekitar 43.38% variabilitas pertumbuhan ekonomi dapat dijelaskan oleh model ini. Hasil F-statistic sebesar 7.279 dengan p-value 0.004499 memberikan indikasi signifikansi keseluruhan model. Dengan demikian, model ini menyiratkan bahwa ekspor dan impor memiliki dampak yang signifikan terhadap pertumbuhan ekonomi Indonesia, namun penting untuk memahami bahwa interpretasi sebab-akibatnya perlu diterjemahkan dengan hati-hati dan mempertimbangkan konteks ekonomi yang lebih luas.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<ol type="a">
<li><p>Hasil analisis statistik menunjukkan adanya hubungan positif antara jumlah ekspor dengan pertumbuhan ekonomi di Indonesia. Koefisien positif untuk variabel ekspor (5.770e-05) menegaskan bahwa peningkatan ekspor berkontribusi positif terhadap pertumbuhan ekonomi, meskipun terdapat hubungan negatid antara Impor dengan pertumbuhan ekonomi indonesia</p></li>
<li><p>Koefisien regresi positif pada variabel ekspor memberikan indikasi bahwa peningkatan aktivitas perdagangan internasional dapat mendorong pertumbuhan ekonomi Indonesia. Temuan ini dapat menjadi landasan penting dalam merancang kebijakan ekonomi dan perdagangan untuk memperkuat peran ekspor dan impor dalam mendukung pertumbuhan ekonomi negara.</p></li>
</ol>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Adrian Sutedi, S. H. (2014). Hukum Ekspor Impor. RAS.</p>
<p>Berata, I. K. O. (2014). Panduan Praktis Ekspor Impor. RAS.</p>
<p>Pridayanti, A. (2014). Pengaruh ekspor, impor, dan nilai tukar terhadap pertumbuhan ekonomi di Indonesia periode 2002-2012. Jurnal Pendidikan Ekonomi (JUPE), 2(2).</p>
<p>Sasono, H. B. (2021). Manajemen Pelabuhan dan Realisasi Ekspor Impor. Penerbit Andi.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>